apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: xbopko-ambulance-ufe-content
spec:
  microFrontend: xbopko-ambulance-ufe
  element: cv2-ambulance-wl-list
  attributes:
    - name: base-path
      value: /cv2-ambulance-wl/
    - name: api-base
      value: http://localhost:5000/api
    - name: ambulance-id
      value: bobulova
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?xbopko-ambulance-wl(/.*)?$"